### ISSUE TITLE
get_indice_graph question

### ISSUE THREAD

**Issue by detectiveli** [divelab/lgcn#8]
Such a brilliant work on sub-graph.

As I read the code in get_indice_graph line 11-14, do you mean to choose the node based on the new nodes we added last while loop? Cause when I debug here, if we use pre_indices = indices, they will share a same pointer and be the same all the time. So it will break after the first iteration in while loop. Could you please give me some advice anything I misunderstanding?

Thank you very much!

**Comment by HongyangGao** [comment]
Hi, you are right. Since this is a process of expanding graph using some given center nodes. In each iteration, we want to expand some nodes that are connected to the new added nodes in the last iteration. You can also see this process from Figure 4 in the paper (https://arxiv.org/pdf/1808.03965.pdf).
